name: Checks

on:
  push:
    branches:
      - master
      - develop
    tags:
      - v*
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  checks:
    uses: lirios/.github/.github/workflows/checks.yml@master
    with:
      enable_wip: true
      enable_reuse: true
